language: node_js
node_js:
- '20'
script: npm test
before_deploy: echo 'All unit tests passed; Successfully built distribution assets;
  Preparing to deploy DGX Patron Creator Service to AWS.'

services:
  - postgres
before_script:
  - npm install
  - psql -c 'create database barcodes_test;' -U postgres
script:
  - TRAVIS=true npm run test

deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully executed deploy trigger for DGX Patron Creator Service
  on AWS'
env:
  global:
    secure: aSJ9s8mAZNUgElwfK7mm9uDV1MwJqH/cy8w0xOqO4aewEb6lFBLIfXZa+VeUxoKj8AXlZSIfcdIApahsAZXp9p4gmX1U+DonYVF6kVN1heTvQgce/j6CV16eULvZami8fisohS30PPjOoFNaDDAQbnBlSFTkwVG1ELHhKlXCfGR2pq18WbCTiFVCF+2EpqfO0PXPOBM2Z7jqXqPuZJDJjXhcglLjCCcWron9GAzC36nm+WLrCZXTpfXGQ8Owba4G62hp/LKB27apYL1o0dJwgTw5jyT+d9FIt4RbMBnzLHqPkz2cvBxkKwcZWUXwmdnEEH3gkrrO/V4ln0BQemiCuUtKhei/u4nMJUCgeUuQc5lmw+XjPvMNkZUS+bAdho/z8mYREaSGM0zNUPwqPgpc/tr0I7qsuIbrariV9Di7P3812Qi/mLIfC9dCN6vTiPrQ8/yJg+yygelaJPydo1mEuTLYuR+MoRpz/o/Esnf9vsmUM80VmnR3CAZCo3PV02RNOKunwHo2LChZROJNkcIJldAJeM1zOn0GcMIfUhC0JmMqhfWf9huSnaCMgekSWU+RC3TZceV3y8/+WLPFDrpMvwjXkUU1Cq28T9aobLXBN9P9daVm0+/omWtwHpMkzddYyfV7kQN+OQt+5ZERAC3BglCsKU+2x5F8PqrH/Fq8pKo=
