name: Test and Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node version
        uses: actions/setup-node@v4
        with: 
          node-version-file: .nvmrc
      - name: npm install 
        run: npm ci
      - name: Run tests
        run: npm test
  deploy-qa:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    needs: test
    if: github.ref == 'refs/head/qa'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node20
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: Deploy app to QA
        run: |
          terraform -chdir=lambda/provisioning/qa init -input=false
          terraform -chdir=lambda/provisioning/qa apply -auto-approve -input=false